### ISSUE TITLE
Pokemon Spawning errors

### ISSUE THREAD

**Issue by Burgersim** [DansDatapacks/Pokemon-Fishing#1]
Hi, unfortunately it seems this pack is not working correctly in the newest version. When I should catch a pokemon, I just get an error and the error texture block.

It says to check the logs, but I don't really see anything other than the message itself in my game or on the server...

Tried it three times now, Krabby, Basculin and Magicarp didn't spawn but instead I got these "error" items, that don't really say more than just to report it

Oh it does say something like 
`Error: Failed to Spawn Pokemon (1-89-14-2519)` for example, that would be Krabby I think

**Comment by Dariensg** [comment]
Can confirm, this is happening on my server as well

**Comment by Dan-Mizu** [comment]
This has been an issue since the pack released, and must be related to a bug where datapacks can't seem to use the `/spawnpokemon` command on servers. I implemented a workaround where the datapack will attempt to run `/reload` until the error goes away, but I do not recommend enabling it unless you're on a fabric or forge server without too many mods. Regardless, the command is: `/function #pokemonfishing:reload_on_error`. Then run `/reload` after enabling it for it to take effect.

**Comment by Burgersim** [comment]
That is a good workaround, but since I have about 50 mods, I think it's probably not good for my server unfortunately. So I guess that means I'll have to wait on a new Cobblemon release to fix that bug then?

**Comment by Dan-Mizu** [comment]
> That is a good workaround, but since I have about 50 mods, I think it's probably not good for my server unfortunately. So I guess that means I'll have to wait on a new Cobblemon release to fix that bug then?

I wouldn't hold my breath. I'd say give it a try to see if it works without any downsides, otherwise your only option then is to wait.

**Comment by Kevinello** [comment]
Any progress here?
I play with luckperm installed, and i have given cobblemon.command.spawnpokemon to default group, but the error still exists.

**Comment by Dan-Mizu** [comment]
[A fishing mechanic has been teased](https://youtu.be/Pylu2P9a_EU?si=QekIFrwDankQjRhR) for following versions of Cobblemon. I will no longer add any new features to this pack. 

There has been a longstanding seemingly unfixable issue typically server owners more often on the Forge platform face where cobblemon fail to spawn when fished. The band-aid solution was to run the `/reload` command until it fixed itself, which my pack had the ability to check for automatically. However that has its own problems as well.

Hopefully the issue where datapacks are unable to spawn cobblemon gets ironed out in the future so packs could take advantage of that.
